apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "fullname" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.tarport }}
    # nodePort: {{ .Values.service.nodeport }}

